var models = require("./../models");

var getAllTasksForAUser = function (userId, callback) {
  models.tasks.findAll({
      where: {
      userId: Number(userId) //incase taskId is given as string, userId generated by relationship declaration in database.js
      }
    })
    .then(function (result) {
      var resArr = [];
      result.forEach(function (res) {
        resArr.push(res.dataValues); //grab the data values out to return later
      });
      callback(null, resArr);
    })
    .error(function(error) {
      callback(error);
    });
}


//Add all functions to the export object
var exp = {};
exp.getAllTasksForAUser = getAllTasksForAUser;

module.exports = exp;